### PR TITLE
Add options to enable LDAPS and START_TLS

### PR DESCRIPTION
**Pull request by kapdap**
Added options to enable LDAP, START_TLS and set the LDAP port number.

### CODE REVIEW

**Comment by benyanke** [comment]
Thank you! This has been on my backlog to do, so I appreciate the help.

**Comment by benyanke** [comment]
Have not tested the running code, but it looks good overall.

Minor suggestion: make the default port selected based on the protocol, then only need to specify to override that.

Minor thing though - I'll add that before merge (unless you get to it first). Otherwise, looks good! Will give it a test, add that port feature, and get it merged in.

**Comment by kapdap** [comment]
The python ldap3 library takes care of default port selection based on the provided uri schema, so I left it up to the library to work out the appropriate setting.

Added a check in the case LDAP_PORT wasn't set as the int function expects a value.

Also, thanks for the extra work you've done on the image.

**Review by benyanke — APPROVED** [review]
Looks good to me - will merge and test.

**Comment by benyanke** [comment]
Thanks again!

**Pull request merged**
